### ISSUE TITLE
TOmniThreadPool.CancelAll doesn't cancel scheduled tasks

### ISSUE THREAD

**Issue by HJRunhaar** [gabr42/OmniThreadLibrary#100]
When calling TOmniThreadPool.CancelAll (while all threads in the pool are busy) all running tasks are cancelled (OK), after that scheduled tasks are started and executed (not OK).
 
Expected behaviour is that scheduled tasks are cancelled as well and not executed.

**Comment by gabr42** [comment]
By my tests (see https://www.dropbox.com/s/5k7zfuvggsyllnv/Project78.zip?dl=0) CancelAll works fine.

Please attach a minimal compilable program that exhibits the problem.

**Comment by HJRunhaar** [comment]
I delved deeper into this problem and I found that our own threads needed an additional termination check. 
So no problem at the OTL side. Sorry, this is a non-issue.
