### ISSUE TITLE
Implementation of SetOptions is missing if OTL_NUMASupport is not set

### ISSUE THREAD

**Issue by CWBudde** [gabr42/OmniThreadLibrary#101]
For an older project I have undefined OTL_NUMASupport. Unfortunately the implementation of TOmniThreadPool.SetOptions is placed a bit wrong, which means that it is excluded as well (resulting in a compiler error).

It's not difficult to fix (just move it up or down a bit), so I haven't included a patch here.

**Comment by gabr42** [comment]
Ups! Thanks!
