### ISSUE TITLE
Tasks are taking too long to be executed after 3.07.1 release.

### ISSUE THREAD

**Issue by cesarliws** [gabr42/OmniThreadLibrary#102]
I have a Windows Service with some tasks, I create a TaskGroup and add a few tasks, the tasks can run as TaskControl.Run, TasksControl.Schedule or using Timers, mostly using Timers.

When I run as Application, it is all OK, but when running as Windows services, it is taking about 60 seconds to trigger the tasks, I have changed the tasks priority to tpHigher with no results.

After I removed the 3.07.1 release using GetIt, and pointed in Library Path to my repository with a few months older version of OTL, it is working fine again.

**Comment by gabr42** [comment]
I need a reproducible example.
