### ISSUE TITLE
Setting value for Locked<T>?

### ISSUE THREAD

**Issue by VyPu** [gabr42/OmniThreadLibrary#103]
Hello,

I like the ```Locked<T>``` from ```otlSync.pas``` unit, but I have some problems in understanding how should I use it. I could not find a complete usage example, therefore decided to ask here.

Let's say I have a variable ```MyVar```: 
```
var
  MyVar: Locked<Integer>;
```
If I want to retrieve a value of MyVar I write the following code:
```
MyVar.Acquire;
try
  CopyOfMyVar := MyVar.Value;
finally
  MyVar.Release;
end;
```
If I want to assign a value to MyVar, let's say 5, I write
```
MyVar.Acquire;
try
 MyVar.Value := 5;
finally
  MyVar.Release;
end;
```
But this code will not compile as the ```Locked<T>.Value``` property is read-only. Of course I can edit the implementation of ```Locked<T>``` and add ```SetValue``` procedure my self, but I guess this would change the original design idea. So, is there any particular reason not to have a write access to the ```Value``` property? And if yes, could you suggest a better way to set the value in multithreaded environment?

**Comment by gabr42** [comment]
Locked<T> is documented in the book (http://leanpub.com/omnithreadlibrary). You can read about it online here: http://otl.17slon.com/book/chap06.html#synch-criticalsections-lockedt

**Comment by VyPu** [comment]
Primož, thank you for the links. In fact, I have already read this chapter many times. It is quite clear how to read the Value, but setting the value is not so clear. Do I understant it right, that the value is set only by using constructors and implicit operators (which internally also call constructors)? 

If yes, then could you comment how to set the value in a ```Locked(proc: TProcT)``` procedure? Or in cases when I want to do several operations with the variable, without releasing the critical section? The constructors reset all the locks. In my opinion writable ```.Value``` property would be very useful, but it might be, that I am missing something.

**Comment by gabr42** [comment]
The idea behind Locked<T> is to provide a locked access to a static value, typically an object or an interface. Hence, it doesn't support changing the Value.

**Comment by VyPu** [comment]
OK, now I understand. Do you expect any problems if I manually add SetValue procedure and use it for, let's say strings, records and other regular types?

**Comment by gabr42** [comment]
If you wrap the change in Acquire/Release internally, it should work. If you submit such a change as a pull request, I'll probably include it in the code (have to think a bit more about possible problems that could occur).

**Comment by VyPu** [comment]
Actually, I was thinking about such procedure:

```
procedure Locked<T>.SetValue(const value: T);
begin
  Assert(FLock.LockCount > 0, 'Locked<T>.SetValue: Not locked');
  FValue := value;
end;
```

The style is very simmilar to the ```GetValue``` function, and does not include Acquire/Release. In this way, it becomes possible to perform several operations with the Value without unlocking it. If you agree, I can try to do the pull request.

**Comment by gabr42** [comment]
Yes, that is also a possibility and the owner can take care of locking. Go ahead.

**Comment by VyPu** [comment]
Hi, 

Thanks for merging SetValue to the main branch! 

I was using it for some time already and it worked fine. However, sometimes I get a bit lazy in writing the try .. finally blocks around the Value, when I need to perform only a single operation with it. 

What do you think, would it be worth adding another property, e.g. ```LockedValue``, to the Locked<T> structure? At least for my code it would save many lines :) 


```
function Locked<T>.GetLockedValue: T;
begin
  FValue.Acquire;
  try
    Result := FValue;
  finally
    FValue.Release;
  end;
end; 

procedure Locked<T>.SetLockedValue(const value: T);
begin
  FValue.Acquire;
  try
    FValue := value;
  finally
    FValue.Release;
  end;
end; 
```

**Comment by gabr42** [comment]
I decided not to add this additional functionality.
