### ISSUE TITLE
Designtime packages are inapropriate for automatic installator

### ISSUE THREAD

**Issue by DmLam** [gabr42/OmniThreadLibrary#104]
In all  **OmniThreadLibraryDesigntime.dproj** files in the packages directory there is a line

`    <DCC_UsePackage>vclx;vcl;OmniThreadLibraryRuntimeXE;OmniThreadLibraryRuntimeXE4;OmniThreadLibraryRuntimeXE6;OmniThreadLibraryRuntimeXE8;$(DCC_UsePackage)</DCC_UsePackage>
`

which make dcc32 compiler (Berlin 10.1 in my case) to fail with message _OmniThreadLibraryRuntimeXE not found_ when I use automatic packages installer (Delphi Package Installer, [https://bitbucket.org/idursun/delphipi](url)). There is no problem if I install the package into IDE manually.
I don't know why it is happens, but it is obviously that dependecies from XE, XE4, XE6 and XE8 is wrong here (when I remove them from .dproj everything works well).

**Comment by gabr42** [comment]
Please commit a pull request for fixed .dproj. Thanks!

**Comment by DmLam** [comment]
Done
