### ISSUE TITLE
Exception in IOmniFuture.Value after calling from another task

### ISSUE THREAD

**Issue by sebomozd** [gabr42/OmniThreadLibrary#107]
OmniThreadLibrary 3.07.4, exception "Exception in TOmniEventMonitorPool.Release: Monitor is not allocated for thread xxxx" after calling IOmniFuture.Value from another task.

Example code:
procedure TForm1.Button1Click(Sender: TObject);
var
  Future, Future2: IOmniFuture<String>;
begin
  Future := Parallel.Future<String>(
    function: String
    begin
      result := 'Test 12345';
    end
  );
  Future2 := Parallel.Future<String>(
    function: String
    begin
      result := Future.Value; //exception here
    end
  );
  memo1.Lines.Add(Future2.Value);
end;

**Comment by gabr42** [comment]
In a current implementation, Future expects that a future is created and used in the same thread. (IOW, same thread creates the future and calls .Value.).

This is not a best idea and I'll look into changing that.

You can change your code a bit and then it works:

procedure TForm17.Button1Click(Sender: TObject);
var
  Future2: IOmniFuture<string>;
begin
  Future2 := Parallel.Future<string>(
    function: string
    var
      Future: IOmniFuture<string>;
    begin
      Future := Parallel.Future<string>(
        function: string
        begin
          result := 'Test 12345';
        end);

      result := Future.Value; // exception here
    end);
  memo1.Lines.Add(Future2.Value);
end;

**Comment by sebomozd** [comment]
Thank you. My code works with OmniThreadLibrary 3.07.1, maybe it can help you.
