### ISSUE TITLE
Lazarus support?

### ISSUE THREAD

**Issue by lainz** [gabr42/OmniThreadLibrary#112]
Hi, is possible to run this library on Lazarus FPC?

**Comment by gabr42** [comment]
No idea but most probably no.

**Comment by lainz** [comment]
No problem, I found a solution already.

`TThread.ExecuteInThread(@SendMail, @SendMailTerminate);`

Is not as advanced, but it works the way I need.

**Comment by TangMonk** [comment]
why not support lazarus?

**Comment by gabr42** [comment]
Because it does not support generics and anonymous methods.

**Comment by TangMonk** [comment]
@gabr42 seems Lazarus support Generics: http://wiki.freepascal.org/Generics, but there is a little different with Delphi

**Comment by dtamade** [comment]
There needs to be a layer of compatibility
