### ISSUE TITLE
Correct release date ;-)

### ISSUE THREAD

**Issue by jaclas** [gabr42/OmniThreadLibrary#113]
In history file:

3.07.5: 2017-02-28

**Comment by gabr42** [comment]
Re: [gabr42/OmniThreadLibrary] Correct release date ;-) (#113)






In history file:
3.07.5: 2017-02-28
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



2017 :) :) :)

Thanks!

Primož

**Comment by gabr42** [comment]
:) :) :)

Fixed.
