### ISSUE TITLE
x64. Invalid function API prototype declaration. Invalid parameters passing. FIXES

### ISSUE THREAD

**Issue by MkhPavel** [gabr42/OmniThreadLibrary#122]
There are several bugs in API prototype declaration and procedure parameters passing, 
which I've found out and fixed while was developing under x64.

1. ------------------------------------------------------------	  

// Cardinal > WPARAM, LPARAM, LRESULT

  function DSiClassWndProc(Window: HWND; Message: cardinal;
->    aWParam: **WPARAM**; aLParam: **LPARAM**): **LRESULT**; stdcall;

2. ------------------------------------------------------------	  

WPARAM, LPARAM

  TOmniContainerWindowsMessageObserver = class(TOmniContainerObserver)
  strict protected
    function  GetHandle: THandle; virtual; abstract;
  public
->>    procedure Send(aMessage: cardinal; wParam: **WPARAM**; lParam: **LPARAM**); virtual; abstract;
    property Handle: THandle read GetHandle;
  end; { TOmniContainerWindowsMessageObserver }

3. ------------------------------------------------------------	    

WPARAM, LPARAM

  TOmniContainerWindowsMessageObserverImpl = class(TOmniContainerWindowsMessageObserver)
  strict private
    cwmoHandle  : THandle;
->  cwmoLParam  : **LPARAM**;
    cwmoMessage : cardinal;
->  cwmoWParam  : **WPARAM**;
  strict protected
    function  GetHandle: THandle; override;
->>    procedure PostWithRetry(msg: UINT; wParam: **WPARAM**; lParam: **LPARAM**);
  public
->>    constructor Create(handle: THandle; aMessage: cardinal; wParam: **WPARAM**; lParam: **LPARAM**);
->>    procedure Send(aMessage: cardinal; wParam: **WPARAM**; lParam: **LPARAM**); override;
    procedure Notify; override;
  end; { TOmniContainerWindowsMessageObserver }
  
4. ------------------------------------------------------------	     

WPARAM, LPARAM

  function CreateContainerWindowsMessageObserver(hWindow: THandle; msg: cardinal;
->    wParam: **WPARAM**; lParam: **LPARAM**): TOmniContainerWindowsMessageObserver;

	
5. -----------------------------------------------------------	

// cardinal -> NativeUInt, not critical of cause	

procedure TGpLockFreeQueue.Initialize;
begin
  obcTailPointer := AllocateAligned(SizeOf(TGpLFQueueTaggedPointer), 4, obcTailBuffer);
  obcHeadPointer := AllocateAligned(SizeOf(TGpLFQueueTaggedPointer), 4, obcHeadBuffer);
  obcCachedBlock := AllocateBlock; // pre-allocate memory
  obcTailPointer.Slot := NextSlot(AllocateBlock); // point to the sentinel
  obcTailPointer.Tag := obcTailPointer.Slot.Tag;
  obcHeadPointer.Slot := NextSlot(obcTailPointer.Slot);
  obcHeadPointer.Tag := obcHeadPointer.Slot.Tag;
-> Assert(**NativeInt**(obcTailPointer) mod 8 = 0);
-> Assert(**NativeInt**(obcHeadPointer) mod 8 = 0);
-> Assert(**NativeInt**(@obcCachedBlock) mod 4 = 0);
end; { TGpLockFreeQueue.Initialize }	

6. -----------------------------------------------------------	

// cardinal > LPARAM	

procedure TOTPWorker.ForwardThreadCreated(threadID: TThreadID);
begin
  {$IFDEF MSWINDOWS}
  if assigned(owMonitorObserver) then
->>    owMonitorObserver.Send(COmniPoolMsg, 0, **LPARAM**
        (TOmniThreadPoolMonitorInfo.Create(owUniqueID, tpoCreateThread, 
		  threadID)));
  {$ENDIF MSWINDOWS}
end; { TOTPWorker.ForwardThreadCreated }

7. -----------------------------------------------------------	

// cardinal > LPARAM	

procedure TOTPWorker.ForwardThreadDestroying(threadID: TThreadID;
  threadPoolOperation: TThreadPoolOperation; worker: TOTPWorkerThread);
begin
  if not assigned(worker) then
    worker := LocateThread(threadID);
  if assigned(worker) then begin
    task.UnregisterComm(worker.OwnerCommEndpoint);
    worker.Stopped := true;
  end;
  {$IFDEF MSWINDOWS}
  if assigned(owMonitorObserver) then
->    owMonitorObserver.Send(COmniPoolMsg, 0, **LPARAM**
      (TOmniThreadPoolMonitorInfo.Create(owUniqueID, threadPoolOperation,
        threadID)));
  {$ENDIF MSWINDOWS}
end; { TOTPWorker.ForwardThreadDestroying }	

8. -----------------------------------------------------------

// cardinal > LPARAM	

procedure TOTPWorker.ProcessCompletedWorkItem(workItem: TOTPWorkItem);
var
  worker: TOTPWorkerThread;
begin
  worker := workItem.Thread;
  {$IFDEF LogThreadPool}Log('Thread %s completed request %s',
    [worker.Description, workItem.Description]); {$ENDIF LogThreadPool}
  if owDestroying then begin
    FreeAndNil(workItem);
    Exit;
  end;
  {$IFDEF LogThreadPool}
  Log('Thread %s completed request %s', [worker.Description, workItem.Description]);
  Log('Destroying %s', [workItem.Description]);
  {$ENDIF LogThreadPool}
  {$IFDEF MSWINDOWS}
  if assigned(owMonitorObserver) then
->    owMonitorObserver.Send(COmniPoolMsg, 0, **LPARAM**
     (TOmniThreadPoolMonitorInfo.Create(owUniqueID, workItem.UniqueID)));
  {$ENDIF MSWINDOWS}
  FreeAndNil(workItem);
	
9.  -----------------------------------------------------------	
	
passing the UniqueID as msg wParam\lParam

procedure TOmniTask.InternalExecute(calledFromTerminate: boolean);
...
begin
...       
        otSharedInfo_ref.MonitorLock.Acquire;
        try
          sync := otSharedInfo_ref.MonitorLock.SyncObj;
          {$IFDEF MSWINDOWS}
          if assigned(otSharedInfo_ref.Monitor) then
**->>           {$IFDEF CPUX64}
->>            otSharedInfo_ref.Monitor.Send(COmniTaskMsg_Terminated, WPARAM(UniqueID), 0);
->>           {$ELSE}
->>            otSharedInfo_ref.Monitor.Send(COmniTaskMsg_Terminated, WPARAM(Int64Rec(UniqueID).Lo), LPARAM(Int64Rec(UniqueID).Hi));           
->>           {$ENDIF}** 
          {$ENDIF MSWINDOWS}
          otSharedInfo_ref := nil;
        finally sync.Release; end;
      end
	  
function TOmniTaskControl.SetMonitor(hWindow: THandle): IOmniTaskControl;
begin
  if not assigned(otcSharedInfo.Monitor) then begin
    if otcParameters.IsLocked then
      raise Exception.Create('TOmniTaskControl.SetMonitor: Monitor can only be assigned while task is not running');
    EnsureCommChannel;
**->>   {$IFDEF CPUX64}
->>    otcSharedInfo.Monitor := CreateContainerWindowsMessageObserver(hWindow, COmniTaskMsg_NewMessage, wParam(UniqueID), 0);
->>   {$ELSE}
->>    otcSharedInfo.Monitor := CreateContainerWindowsMessageObserver(hWindow, COmniTaskMsg_NewMessage, WPARAM(Int64Rec(UniqueID).Lo), LPARAM(Int64Rec(UniqueID).Hi));
->>   {$ENDIF}**
    otcSharedInfo.CommChannel.Endpoint2.Writer.ContainerSubject.Attach(
      otcSharedInfo.Monitor, coiNotifyOnAllInserts);
  end
  else if otcSharedInfo.Monitor.Handle <> hWindow then
    raise Exception.Create('TOmniTaskControl.SetMonitor: Task can be only monitored with a single monitor');
  otcSharedInfo.Monitor.Activate;
  Result := Self;
end; { TOmniTaskControl.SetMonitor }

10.  -----------------------------------------------------------	
	
extracting the UniqueID from wParam\lParam of msg passed

procedure TOmniEventMonitor.WndProc(var msg: TMessage);
...
	
**->>  function GetUniqueID(const AMsg: TMessage): Int64;
->>  begin
->>   {$IFDEF CPUX64}
->>    Result := AMsg.wParam;
->>   {$ELSE}
->>    Int64Rec(Result).Lo := AMsg.wParam;
->>    Int64Rec(Result).Hi := AMsg.lParam;
->>   {$ENDIF}
->>  end;**

begin { TOmniEventMonitor.WndProc }
  if msg.Msg = COmniTaskMsg_NewMessage then 
  begin
**->>    if Supports(emMonitoredTasks.ValueOf(GetUniqueID(msg)), IOmniTaskControl, Task) then**
    //task := emMonitoredTasks.ValueOf(Pint64(@msg.WParam)^) as IOmniTaskControl;
    //if assigned(task) then 
	begin
      timeStart := GetTickCount;
      ProcessMessages;
    end;
    msg.Result := 0;
  end
  else if msg.Msg = COmniTaskMsg_Terminated then 
  begin
**->>    if Supports(emMonitoredTasks.ValueOf(GetUniqueID(msg)), IOmniTaskControl, Task) then**
    //task := emMonitoredTasks.ValueOf(Pint64(@msg.WParam)^) as IOmniTaskControl;
    //if assigned(task) then 
    begin
      endpoint := (task as IOmniTaskControlSharedInfo).SharedInfo.CommChannel.Endpoint1;

**Comment by gabr42** [comment]
Can you make pull request out of this, please? I'll merge it in with a great pleasure.

And thank you very much for finding & fixing the bugs!
