### ISSUE TITLE
unit OtlCommon not found

### ISSUE THREAD

**Issue by TangMonk** [gabr42/OmniThreadLibrary#126]
I am installed this package in RAD studio:

![image](https://user-images.githubusercontent.com/3498786/47964423-d9d14980-e074-11e8-919f-19206408f8df.png)

and then create an empty VCL form project, then include the `OtlCommon`
![image](https://user-images.githubusercontent.com/3498786/47964437-23ba2f80-e075-11e8-81da-1d6fd8406b17.png)

the error shows to me:

```
Unit `OtlCommon` not found

```

![image](https://user-images.githubusercontent.com/3498786/47964441-37fe2c80-e075-11e8-8a21-2ba993375197.png)

**Comment by gabr42** [comment]
Add folder with OTL source files to project's Search path or to IDE Library path.
