### ISSUE TITLE
Missing parallel.ForEach for IEnumerator<T>and IEnumerable<T>

### ISSUE THREAD

**Issue by HHasenack** [gabr42/OmniThreadLibrary#129]
missing an overloaded routine
`class function  ForEach<T>(const enum: IEnumerator<T>): IOmniParallelLoop; overload;`

Instead the compiler decides to use
`class function  ForEach<T>(const enum: IEnumerator): IOmniParallelLoop; overload;`

Which results in internally the wrong GetCurrent routine being called (the one that returns a `TObject ` rather than the one with type `T`

I have managed to create a workaround by creating a `TEnumerator<T>` wrapper class around the `IEnumerator<T>` interface, and this works ok for the interfaces that I want to pass to the worker threads. (see other issue, for a required patch on otlCommon).

But it would be so much better and cleaner in my app code to have direct `parallel.ForEach` support for the` IEnumerator<T>` and `IEnumerable<T>` interfaces directly

**Comment by gabr42** [comment]
Thanks a lot!
