### ISSUE TITLE
Task.Invoke not always runs in main thread

### ISSUE THREAD

**Issue by Sorien** [gabr42/OmniThreadLibrary#142]
```pascal
procedure TSqlVirtualizedAdapter.LoadCount();
begin
  LastCountTask := FCountTask;

 Assert(GetCurrentThreadId = MainThreadId, 'UI controls like ' + Classname + ' should only be manipulated through the main thread.'); // it will never assert here

  FCountTask := CreateTask(
    procedure(const Task: IOmniTask)
    begin
      if Assigned(LastCountTask) then
        LastCountTask.Terminate;

      if Task.Terminated then
        Exit;

//do some work

      if (not Task.CancellationToken.IsSignalled) and (not Task.Terminated) then
        Task.Invoke(
          procedure
          begin
            UpdateCount; //  contains assert   Assert(GetCurrentThreadId = MainThreadId, 'UI controls like ' + Classname + ' should only be manipulated through the main thread.');

          end);
    end).Unobserved.OnTerminated(HandleException);

  Parallel.Start(FCountTask, Parallel.TaskConfig.CancelWith(FCancellationToken));
end;
```

and my users are hitting that assert with call stack

MyComponent:   706 | TVirtualizedBlockAdapter.UpdateCount
-- | --
OtlTaskControl: 3209 | TOmniTaskControl.ForwardTaskMessage
OtlTaskControl: 3759 | TOmniTaskControl.Terminate
SqlAdapter: 404 | TSqlVirtualizedAdapter.LoadCount$ActRec.$0$Body
OtlTaskControl: 2014 | TOmniTaskExecutor.Asy_Execute
OtlTaskControl: 1592 | TOmniTask.InternalExecute
OtlTaskControl: 1515 | TOmniTask.GetCancellationToken
OtlThreadPool: 850 | TOTPWorkerThread.Execute

**Comment by gabr42** [comment]
Task.Invoke does not execute in the main thread. It executes in the threat that owns the task (i.e. in the thread that has called CreateTask).

Maybe your TSqlVirtualizedAdapter.LoadCount is not called from the main thread?

**Comment by Sorien** [comment]
TSqlVirtualizedAdapter is part of vcl component and should be, i'll let assert there to check it but from my tests CreateTask is always called from main thread

**Comment by Sorien** [comment]
@gabr42 CreateTask is always created in main thread, problem is that I can't simulate it myself but see that error in logs like hundreds of times per day.

**Comment by Sorien** [comment]
maybe I cant terminate one thread from another thread?

**Comment by gabr42** [comment]
You cannot terminate one thread from another thread.

It seems that the messages are processed in a window belonging to a wrong thread, but I have no idea how that can happen and what is going on.

Unless you can reproduce a problem in a test case, I can't help. Sorry :(

**Comment by Sorien** [comment]
the problem seems to be in terminating from different thread than task creation thread (main thread) Task.Invoke seems to run after termination in a thread that terminates task.

**Comment by gabr42** [comment]
Ah, that would explain it! 

Indeed, currently you should always terminate the task from the same thread it was created in.

If that is a problem, you can use some other way to trigger a task termination, for example [TerminateWhen](http://www.omnithreadlibrary.com/book/chap07.html#lowlevel-tomniworker-terminateWhen).
