### ISSUE TITLE
OtlParallel.pas(3884): E2010 Incompatible types: 'TObject' and 'IOmniTaskControl'

### ISSUE THREAD

**Issue by AgnenW** [gabr42/OmniThreadLibrary#144]
![error](https://user-images.githubusercontent.com/66155103/83320448-fbda8000-a247-11ea-8721-42e8fea8d6bf.JPG)

**Comment by LingamYoni** [comment]
http://docwiki.embarcadero.com/RADStudio/Sydney/en/New_features_and_customer_reported_issues_fixed_in_RAD_Studio_10.4#FreeAndNil

**Comment by gabr42** [comment]
Fixed, thank you for the report.
