### ISSUE TITLE
Add function IOmniTaskCOntrol.DirectExecute:IOmniTaskCOntrol

### ISSUE THREAD

**Issue by HHasenack** [gabr42/OmniThreadLibrary#145]
Take a look at stackoverflow why this makes sense:

https://stackoverflow.com/questions/62327719

And find the modified file attached in this issue. Look for HH_PATCH for my changes.

[OtlTaskControl.zip](https://github.com/gabr42/OmniThreadLibrary/files/4782313/OtlTaskControl.zip)

**Comment by gabr42** [comment]
This is implemented now, thanks for the code.
