### ISSUE TITLE
Memory Leak (tiny) in example/demo "folder scanner"

### ISSUE THREAD

**Issue by JohnTerwiske** [gabr42/OmniThreadLibrary#146]
Delphi 10.3.3, OmniThreadLibrary 3.07.8.
Windows 32 and 64 bit
![CapturedMemLeak](https://user-images.githubusercontent.com/23263724/85950253-be8e0e80-b929-11ea-9834-0f6f7731bd7c.PNG)

fileinfo of type TFileInfo is not freed.

To reproduce:
1.  add ReportMemoryLeaksOnShutdown := True to project file
2.  Run the Folder Scanner/Pipeline Demo
3.  Select a Folder by clicking the "select button"
4.  "Parallel Scanners" should be "4"
5.  Click the "Start" button, wait from completion
6.  Close program, get report of memory leak (see attached)

**Comment by gabr42** [comment]
Cannot reproduce, sorry.

Next time you encounter this, do the following:
- Add FastMM4 as a first unit of your project (https://github.com/pleriche/FastMM4)
- Define FullDebugMode conditional symbol in your project
- Rebuild and run

When you exit the program, FastMM will generate a detailed report (.txt file) in the exe folder. Please attach that file to the  report.
