### ISSUE TITLE
Error in TOmniMREW.ExitWriteLock

### ISSUE THREAD

**Issue by eaglesw** [gabr42/OmniThreadLibrary#149]
Hello,

I am facing big problem when using TOmniMREW.

There is one reader doing a lengthy operation (approximately 30 seconds elapse between calls TryEnterReadLock and ExitReadLock). At this point, the writer tries to enter the critical section (TryEnterWriteLock with timeout = 10 seconds).
The first attempt fails, which is correct. But the second attempt immediately after the first succeeds (at this moment the reader has not left the critical section yet)!

I looked at the source and found the problem area.

> function TOmniMREW.TryEnterWriteLock(timeout_ms: integer): boolean;
> var
>   currentReference: NativeInt;
>   startWait_ms    : int64;
> 
>   function Timeout(var gotLock: boolean): boolean;
>   begin
>     Result := (timeout_ms <= 0) or DSiHasElapsed64(startWait_ms, timeout_ms);
>     if Result then
>       gotLock := false;
>   end; { Timeout }
> 
> begin
>   Result := true;
>   startWait_ms := DSiTimeGetTime64; //TODO: Rewrite this with a faster, non-locking clock
> 
>   //Wait on writer to reset write flag so omrewReference.Bit0 must be 0 then set omrewReference.Bit0
>   repeat
>     currentReference := NativeInt(omrewReference) AND NOT 1;
>   {$IFDEF MSWINDOWS}
>   until CAS(currentReference,  currentReference + 1, NativeInt(omrewReference))
>         or Timeout(Result);
>   {$ELSE}
>   until (TInterlockedEx.CompareExchange(NativeInt(omrewReference), currentReference + 1, currentReference) = > currentReference) or Timeout(Result);
>   {$ENDIF}
>   if Result then begin
>     //Now wait on all readers
>     repeat
>     until (NativeInt(omrewReference) = 1) or Timeout(Result);
>     if not Result then
>       **ExitWriteLock;   // --------> The problem is here !!!!!!!!!!!!!!!!!!!!!!**
>   end;
> end; { TOmniMREW.TryEnterWriteLock }`

You use the zero bit of "omrewReference" to indicate that the writer has started entering the critical section. In case of failure while waiting for readers, call "ExitWriteLock" that clears not only the zero bit, but all bits. The number of readers is then reset to zero.

> procedure TOmniMREW.ExitWriteLock;
> begin
>   **NativeInt(omrewReference) := 0;**
> end; { TOmniMREW.ExitWriteLock }

I think "ExitWriteLock" should only reset the zero bit. Correct the error, please.

**Comment by gabr42** [comment]
You are entirely correct. I added this bug when implementing the Timeout parameter. ExitWriteLock is still correct as it should only be called when a write lock is actually acquired. The code just shouldn't call it in the case of a timeout.

Thank you for the detailed analysis! I'll fix this ASAP.
