### ISSUE TITLE
Runtime packages are set to Rebuild as needed {$implicitbuild on}

### ISSUE THREAD

**Issue by vincentparrett** [gabr42/OmniThreadLibrary#163]
This causes problems for any other packages taking a dependency on them (via dcp's) - users will get errors like this 

E2466 Never-build package 'XXX' requires always-build package 'OmniThreadLibraryRuntime'

Happy to submit a PR for this, but I will wait for confirmation first.

**Comment by gabr42** [comment]
I didn't know that this setting is causing problems (I really don't understand Delphi packages - they are a black art to me).

Please submit a PR, I'll merge it in.
