### ISSUE TITLE
Delphi 11 Alexandria support

### ISSUE THREAD

**Issue by alan008** [gabr42/OmniThreadLibrary#170]
Hi, Primoz!
Will you add dpk's for new Delphi version 11 ?

**Comment by gabr42** [comment]
I will, as soon as I get D11 installed.

**Comment by alan008** [comment]
Thanks a lot!

**Comment by PeterPanino** [comment]
Hi, Primoz!
Waiting for the Delphi 11 Alexandria packages. Have a nice weekend!

**Comment by alan008** [comment]
Because packages for Alexandria were added to trunk :) Look at [this commit](https://github.com/gabr42/OmniThreadLibrary/commit/58e8081721c8592d2d5b9f9a9dd334210a4cfb9f)
