### ISSUE TITLE
OmniQueue Dequeue problem

### ISSUE THREAD

**Issue by mariohr** [gabr42/OmniThreadLibrary#32]
Sometimes (!) i have this problem happen when i use the TOmniQueue.IsEmpty function.

![image](https://cloud.githubusercontent.com/assets/5240546/7567412/3e5d26dc-f7d3-11e4-9d86-94ad3c4d10ad.png)

![image](https://cloud.githubusercontent.com/assets/5240546/7567470/94b16db8-f7d3-11e4-8817-9fc785f9e778.png)

the object is created, but i dont why this error 'sometimes' happen. the function 'isempty' is called in a timer routine ('SetTimer').

function TAutechManager.StartAutech(pID: Integer; pIP: String; pPort: Word; pScanRate: Integer;
  pExecuteMsg: Cardinal): IOmniTaskControl;
begin
  FAutechWorker[pID] := TAutechWorker.Create(pIP, pPort);
  FAutechTask[pID] := CreateTask(FAutechWorker[pID], pIP);
  Result := FAutechTask[pID];
  FAutechTask[pID].SetParameter('idx',pID);
  FAutechTask[pID].SetParameter('ip',pIP);
  FAutechTask[pID].SetParameter('scan_rate',pScanRate);
  FAutechTask[pID].MonitorWith(EventMonitor);
  //-- varredura da IHM (processar teclado e tela)
  FAutechTask[pID].SetTimer(1, 10, pExecuteMsg);
  FAutechTask[pID].Run;
end;

**Comment by gabr42** [comment]
No reproducible test case.
