### ISSUE TITLE
Under 64 bit builds, memory adresses are still cast to 32-bit cardinals

### ISSUE THREAD

**Issue by PatrickvL** [gabr42/OmniThreadLibrary#45]
In a few places, memory addresses are cast to 32-bit, like so : "cardinal(@"

Under 64 bit builds, this is not correct, it's advisable to use NativeUInt instead.

**Comment by gabr42** [comment]
Where, specifically?

**Comment by PatrickvL** [comment]
TOmniCS.Initialize
Atomic<T>.Initialize

**Comment by gabr42** [comment]
Fixed. Thanks!
