### ISSUE TITLE
Thread-safety issue in TOmniCriticalSection.LockCount

### ISSUE THREAD

**Issue by PatrickvL** [gabr42/OmniThreadLibrary#46]
In TOmniCriticalSection.Release, ocsLockCount is decreased AFTER ocsCritSect.Release. This should be done BEFORE, to prevent a concurrency-issue when a thread-switch leads to a conflicting increment of ocsLockCount in TOmniCriticalSection.Acquire.

**Comment by gabr42** [comment]
A thread can never assume that real lock count and ocsLockCount are in sync. It is equally possible to write bad code if the ocsLockCount is incremented before or after ocsCritSect.Release. The code that uses TOmniCriticalSection must take this into account.
