### ISSUE TITLE
Method Invoke with Taskgroup seems not to work

### ISSUE THREAD

**Issue by ebaptistella** [gabr42/OmniThreadLibrary#47]
I have a OmniTaskGroup with some OmniTaskControl. I want to use the invoke method to notify my tasks:

<pre>
for oMyTask in oMyTaskGroup.Tasks do
  oMyTask.Invoke('MyMethod', oMyObjectParameter);
</pre>
Not worked...

I also tried:
<pre>
oMyTaskGroup.SendToAll(TOmniInternalStringMsg.CreateMessage('MyMethod', oMyObjectParameter));
</pre>

Not have the expected result

Am I doing something wrong?

**Comment by gabr42** [comment]
Please provide a minimal complete example. http://stackoverflow.com/help/mcve

**Comment by ebaptistella** [comment]
I was wrong about the invoke method, in another project he worked.

The SendToAll method really have problem. If have only one TaskControl works well, but if I have more than one task have an "access violation". The second task is finished, check the log:
<pre>
ThreadId: 1 ~> ThreadName: TMyWorkOne#1 ~> Param: TMyWorkOne.GetParam: 
ThreadId: 2 ~> ThreadName: TMyWorkOne#2 ~> Param: TMyWorkOne.GetParam: 
>>> Terminate ~> ThreadId: 2 ~> ThreadName: TMyWorkOne#2 <<<
ThreadId: 1 ~> ThreadName: TMyWorkOne#1 ~> Param: TMyWorkOne.GetParam: Random: 0,737634794320911
ThreadId: 1 ~> ThreadName: TMyWorkOne#1 ~> Param: TMyWorkOne.GetParam: Random: 0,737634794320911
</pre>
Taking advantage, the invoke method could not verify that the method called this implemented in class? Because the method is not implemented the task is terminated...

Code Sample:
<pre>
type
  TForm2 = class(TForm)
    Button1: TButton;
    Button2: TButton;
    Memo1: TMemo;
    procedure FormCreate(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
  private
    oMyTaskGroup: IOmniTaskGroup;
    oMyMonitor: TOmniEventMonitor;
    { Private declarations }
  public
    { Public declarations }
    procedure OmniMonitorOnMessage(const task: IOmniTaskControl; const msg: TOmniMessage);
    procedure OmniMonitorOnTaskTerminated(const task: IOmniTaskControl);
  end;

type
  TMyWorkOne = class(TOmniWorker)
  private
    FParameter: TOmniValue;
  public
    procedure GetParam(const AParameter: TOmniValue);
    procedure Timer; override;
  end;

var
  Form2: TForm2;

implementation

uses
  OtlTask;

{$R *.dfm}


procedure TForm2.Button1Click(Sender: TObject);
begin
  oMyTaskGroup.RunAll;
end;
  
procedure TForm2.Button2Click(Sender: TObject);
var
  oMyTask: IOmniTaskControl;
  sRandom: String;
begin
  Randomize;
  sRandom := Random.ToString;

  // \--- not work ---/
  oMyTaskGroup.SendToAll(TOmniInternalStringMsg.CreateMessage('GetParam', 'Random: ' + sRandom));

//  \--- Work ---/
//  for oMyTask in oMyTaskGroup.Tasks do
//   oMyTask.Invoke('GetParam', 'Random: ' + sRandom);
end;

procedure TForm2.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  if (oMyTaskGroup <> nil) then
  begin
    oMyTaskGroup.TerminateAll;
    oMyTaskGroup := nil;
  end;

  if (oMyMonitor <> nil) then
    FreeAndNil(oMyMonitor);
end;

procedure TForm2.FormCreate(Sender: TObject);
begin
  oMyTaskGroup                := CreateTaskGroup;
  oMyMonitor                  := TOmniEventMonitor.Create(Self);
  oMyMonitor.OnTaskMessage    := OmniMonitorOnMessage;
  oMyMonitor.OnTaskTerminated := OmniMonitorOnTaskTerminated;

  oMyTaskGroup.Add(CreateTask(TMyWorkOne.Create(), TMyWorkOne.ClassName + '#1').SetTimer(1, 1000, @TMyWorkOne.Timer).MonitorWith(oMyMonitor));
  oMyTaskGroup.Add(CreateTask(TMyWorkOne.Create(), TMyWorkOne.ClassName + '#2').SetTimer(1, 1000, @TMyWorkOne.Timer).MonitorWith(oMyMonitor));
end;

procedure TForm2.OmniMonitorOnMessage(const task: IOmniTaskControl; const msg: TOmniMessage);
begin
  Memo1.Lines.Add(Format('ThreadId: %d ~> ThreadName: %s ~> Param: %s', [task.UniqueID, task.Name, msg.MsgData.AsString]));
end;

procedure TForm2.OmniMonitorOnTaskTerminated(const task: IOmniTaskControl);
begin
  Memo1.Lines.Add(Format('Terminate ~> ThreadId: %d ~> ThreadName: %s', [task.UniqueID, task.Name]));
end;

{ TMyWorkOne }

procedure TMyWorkOne.GetParam(const AParameter: TOmniValue);
begin
  FParameter := AParameter;
end;

procedure TMyWorkOne.Timer;
begin
  inherited;

  task.Comm.Send(0, 'TMyWorkOne.GetParam: ' + FParameter);
end;
</pre>

**Comment by gabr42** [comment]
Of course it doesn't work. TOmniInternalStringMsg is, as the name states, internal and you should not use it in the application. Use the 'for' loop.
