### ISSUE TITLE
Wish: ForEach starting from dynamic array directly

### ISSUE THREAD

**Issue by the-Arioch** [gabr42/OmniThreadLibrary#55]
Imagine I read tasks (one per line) via TFile.ReadAllLines('file.txt');

Now how can I start the loop? I need three tedios indirecton layers.

Var v: TOmniValue; c: IOmniBlockingCollection;

{1}  v := TOmniValue.FromArray\<string\>( TArray\<string\>(TFile.ReadAllLines('file.txt')));
{2}  c := TOmniBlockingCollection.Create; c.Add(v);
{3}  Parrallel.ForEach( c )....

To reduce boilerplate it would be nice to have

1:   Parrallel.ForEach\<T\>(const Source: TArray\<T\>);

2: just like there is TOmniCollection.ToArray - there may be  TOmniCollection.FromArray (if there cannot be type-cast operator with generics)

**Comment by gabr42** [comment]
Re: [OmniThreadLibrary] Wish: ForEach starting from dynamic array directly (#55)






Imagine I read tasks (one per line) via TFileReadAllLines('filetxt');
Now how can I start the loop? I need three tedios indirecton layers
Var v: TOmniValue; c: IOmniBlockingCollection;
{1} v := TOmniValueFromArray<string>( TArray<string>(TFileReadAllLines('filetxt')));
{2} c := TOmniBlockingCollectionCreate; cAdd(v);
{3} ParrallelForEach( c )
To reduce boilerplate it would be nice to have
1: ParrallelForEach<T>(const Source: TArray<T>);
2: just like there is TOmniCollectionToArray - there may be TOmniCollectionFromArray (if there cannot be type-cast operator with generics)
—
Reply to this email directly or view it on GitHub.



The fastest way to process a dynamic array is probably

Parallel.For(Low(arr), High(arr)).Execute(
  procedure (i: integer)
  begin
    // do something with arr[i]
  end);

A wrapper that accepts dynamic arrays would be nice, though. Noted.

**Comment by the-Arioch** [comment]
Yes, with concern of speed - sure.

But that wish is about boilerplate and DRY.  Many other primitives have from-array constructors, I was surprised that for each did not.

Also - I think for newbs it should be noted in FAQ and in the book easy to find how to feed array to any primitive via converting it to collection first I think. That is not immediately obvious without prior experience...

**Comment by the-Arioch** [comment]
BTW I made a mistake in that very simple short code, and you did not noticed it either.

it should be 

{2} c := TOmniBlockingCollection.Create; c.Add(v);  >>> c.CompleteAdding(); <<

See, a very simple mistake for newbs again, without stressing the need to wrap the input up - it would not stop. Those are kind of gotchas, tat the wrappers tend to remove :-)

**Comment by the-Arioch** [comment]
Can "2: just like there is TOmniCollection.ToArray - there may be TOmniCollection.FromArray (if there cannot be type-cast operator with generics)" part be adressed too ?

**Comment by gabr42** [comment]
moved to #76
