### ISSUE TITLE
EJoinException should allow to "yank" inner exceptions

### ISSUE THREAD

**Issue by aparamon** [gabr42/OmniThreadLibrary#58]
Currently, EJoinException allows to inspect the inner exceptions via Inner/Count properties. However, it would be nice to be able to yank/pop elements from Inner collection, in order to re-raise these in main thread. It is not possible currently as the exception would suffer double-free.

**Comment by gabr42** [comment]
You mean something like EJoinException.Detach(idx: integer)?

**Comment by aparamon** [comment]
Yes, that (or probably 'EJoinException.DetachInner(idx: integer): Exception') would be it!
