### ISSUE TITLE
Error TOmniCommunicationEndpoint.Send: Queue is full or Code: 1816. Not enough quota

### ISSUE THREAD

**Issue by JayDi85** [gabr42/OmniThreadLibrary#63]
Hello.

I have multi-threads application. Some tasks working at background and produce many logs. Also it wait income commands from main thread. 

Main thread process messages by TOmniEventMonitor.OnTaskMessage. Background tasks send messages by IOmniTask.Comm.Send.

It's work fine with small batch of logs. But then main thread is freeze or can't process all logs, message queues from background tasks is overflow and task will end up with error "TOmniCommunicationEndpoint.Send: Queue is full".

I try to SetQueueSize(10000), but then Windows raise error: "Code: 1816. Not enough quota".

Can I check queue status and wait until queue is not full? Or I need to use another architecture?

**Comment by gabr42** [comment]
You can use SendWait instead of Send.

**Comment by JayDi85** [comment]
Thanks, it's work.

**Comment by JayDi85** [comment]
Thanks, it's works. Well, partially works.

"Queue is full" is gone, but I found how to raise "Code: 1816. Not enough quota" from omni-code.

If you use VCL's control and it capabilities in OnTaskMessage, you can get error like that.

Here example (you can [download test project here](https://yadi.sk/d/tmgaxYm-p4Mt8)). Run task and wait little time:

```
// begin-end update of memo is problem
Memo1.Lines.BeginUpdate;
Memo1.Lines.Add(AMessage.MsgData.AsString);
Memo1.Lines.EndUpdate;
```

Error stack:
```
:74a9c52f KERNELBASE.RaiseException + 0x58
System.SysUtils.RaiseLastOSError(???,???)
System.SysUtils.RaiseLastOSError
System.SysUtils.Win32Check(False)
OtlContainerObserver.TOmniContainerWindowsMessageObserverImpl.Notify
OtlContainerObserver.TOmniContainerSubject.Notify(coiNotifyOnAllInserts)
OtlContainers.TOmniBoundedQueue.Enqueue(???)
OtlComm.TOmniMessageQueue.Enqueue((123, (-123567514776079190, TOmniStringData($11295E8) as IInterface, ovtString)))
OtlComm.TOmniCommunicationEndpoint.SendWait(123,(-123567514776079190, TOmniStringData($11295E8) as IInterface, ovtString),100)
u_TestTaskQueue.TForm64.Button1Click$17179$ActRec.$0$Body(TOmniTask($1163940) as IOmniTask)
OtlTaskControl.TOmniTaskExecutor.Asy_Execute(TOmniTask($1163940) as IOmniTask)
OtlTaskControl.TOmniTask.InternalExecute(False)
OtlTaskControl.TOmniTask.Execute
OtlTaskControl.TOmniThread.Execute
System.Classes.ThreadProc($1171BE0)
System.ThreadWrapper($1131240)
:75b5338a kernel32.BaseThreadInitThunk + 0x12
:77009a02 ntdll.RtlInitializeExceptionChain + 0x63
:770099d5 ntdll.RtlInitializeExceptionChain + 0x36
```

**Comment by gabr42** [comment]
Error 1816 just means that you are sending messages too fast to the main window and you are filling up the Windows message queue. Change the architecture of your program - there's no need to send hundreds of messages each second. Just group them and send them in batches.
