### ISSUE TITLE
[Wish] Implement OnPulse event

### ISSUE THREAD

**Issue by aparamon** [gabr42/OmniThreadLibrary#74]
High-level OTL objects implement ability to run code *in caller thread* upon processing finish, i.e.
```
IOmniParallelLoop.OnStop(stopCode: TProc)
IOmniPipeline.OnStop(stopCode: TProc)
```
It is proposed to implement methods
```
IOmniParallelLoop.OnPulse(Interval: Integer; pulseCode: TProc)
IOmniPipeline.OnPulse(Interval: Integer; pulseCode: TProc)
```
which would call pulseCode *in caller thread* every Interval milliseconds. It would enable easy implementation of progress display, GUI update etc.

**Comment by gabr42** [comment]
I don't think this idea (which basically reimplements task's SetTimer) works well with the concept of high-level abstractions such as For and Pipeline. You can update some shared state from a thread periodically and display it via a TTimer on a form and you'll achieve a same result.

**Comment by aparamon** [comment]
Unfortunately, TTimer requires active message loop which is not necessarily available. On the other hand, intermittent WaitFor doesn't require message loop:
```
while not Pipeline.WaitFor(120) do  // pulse
  Progress.SetCurrent(n);
```
The proposed feature would only provide a better syntax (anonymous function) and unified interface for IOmniParallelLoop and IOmniPipeline.

**Comment by gabr42** [comment]
There's no way that you could preempt execution in a caller thread every XXX ms without the cooperation of the said thread, so no. Just no.
