### ISSUE TITLE
TOmniValue does not drop OwnedObject

### ISSUE THREAD

**Issue by HHasenack** [gabr42/OmniThreadLibrary#75]
e.g. TOmniBaseQueue.Dequeue  calls 

...
tail.Value._ReleaseAndClear
...

So I had a big memory leak and came around dthis routine during debugging:
```
procedure TOmniValue._ReleaseAndClear;
begin
  if IsInterfacedType then begin
    ovIntf._Release;
    RawZero;
  end;
end; { TOmniValue._ReleaseAndClear }
```
It does not drop the owned object, even though it is packaged in an interface . The solution was to alter the TOmniValue.IsInterfacedType method by adding the ovtOwnedObject like this:

```
function TOmniValue.IsInterfacedType: boolean;
begin
  Result := ovType in [ovtInterface, ovtExtended, ovtString, ovtVariant, ovtArray, ovtRecord
       ,ovtOwnedObject // HH Addded ovtOwnedObject

                       {$IFDEF MSWINDOWS}, ovtWideString, ovtAnsiString {$ENDIF}];
end; { TOmniValue.IsInterfacedType }
```

This change also means that when you get the object you should eiteh mark the oimnivalue as not owned or NOT free the object yourself.

Regards - Hans

**Comment by gabr42** [comment]
Is this with a "stock" 3.05 or a git HEAD?

**Comment by HHasenack** [comment]
Is the head frommelen github abortus a week ago in believe. ..



____________________________
Ik ben misschien wat kort van stof: Dit is mobiel verstuurd.


-------- Oorspronkelijk bericht --------
Van: Primož Gabrijelčič <notifications@github.com>
Datum: 22-07-2016 20:40 (GMT+01:00)
Aan: gabr42/OmniThreadLibrary <OmniThreadLibrary@noreply.github.com>
Cc: Hans Hasenack <Hans@sg-assetmanagement.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)


Is this with a "stock" 3.05 or a git HEAD?

**Comment by gabr42** [comment]
Then please create a small compilable program which exhibits the problem.

**Comment by HHasenack** [comment]
Dear Primoz

I took the liberty of extending the unit tests. Tests cases added to TestBlockingCOllection1.pas. Complete compileable sources attached in the rar archive in this mail.

Regards!

Hans Hasenack

S&G Asset Management
Bijsterhuizen 1160b
6546 AS  NIJMEGEN
Tel. +31 (0) 24 – 645 0006
Fax +31 (0) 24 – 366 0254
www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>
[sgpartnerswit_transparentzonderbolklein2012MAIL][cid:image001.jpg@01D0ADC7.5D66F4F0]
Vertrouwt u liever haar of uw eigen data voor strategische beslissingen?
Ontdek het antwoord en meldt u aan voor onze reeks themaseminars: 15 september, 13 oktober en 8 december 2016 .
Meer informatie en aanmelden via onze website: www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>

Van: Primož Gabrijelčič [mailto:notifications@github.com]
Verzonden: zondag 24 juli 2016 11:59
Aan: gabr42/OmniThreadLibrary <OmniThreadLibrary@noreply.github.com>
CC: Hans Hasenack <Hans@sg-assetmanagement.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)


Then please create a small compilable program which exhibits the problem.

**Comment by gabr42** [comment]
Sorry, there was no attachment.

**Comment by HHasenack** [comment]
Hi Primoz

STrange! There is an attachment in the mail in my sent items folder.It’s  Called “unittests.rar”. I have attached tot his mail as well… I have also repacked it as a zip file and attache dit tot his mail as well.

Please let me kno wit itr arrives correctly now.

Regards,

Hans Hasenack

S&G Asset Management
Bijsterhuizen 1160b
6546 AS  NIJMEGEN
Tel. +31 (0) 24 – 645 0006
Fax +31 (0) 24 – 366 0254
www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>
[sgpartnerswit_transparentzonderbolklein2012MAIL][cid:image001.jpg@01D0ADC7.5D66F4F0]
Vertrouwt u liever haar of uw eigen data voor strategische beslissingen?
Ontdek het antwoord en meldt u aan voor onze reeks themaseminars: 15 september, 13 oktober en 8 december 2016 .
Meer informatie en aanmelden via onze website: www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>

Van: Primož Gabrijelčič [mailto:notifications@github.com]
Verzonden: maandag 25 juli 2016 09:34
Aan: gabr42/OmniThreadLibrary <OmniThreadLibrary@noreply.github.com>
CC: Hans Hasenack <Hans@sg-assetmanagement.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)


Sorry, there was no attachment.

**Comment by gabr42** [comment]
Also no attachment. :( Please send an email directly to gabr42@gmail.com, that should work.

**Comment by HHasenack** [comment]
It was refused (even by gmail) because of some potential dangerous malware. So I dropped everything from the archive except pas and dpr files.

I sen dit to both addresses now, lets hop it gets through this time. Otherwise I send you the unit test pas file only … :s


Met vriendelijke groet,

Hans Hasenack

S&G Asset Management
Bijsterhuizen 1160b
6546 AS  NIJMEGEN
Tel. +31 (0) 24 – 645 0006
Fax +31 (0) 24 – 366 0254
www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>
[sgpartnerswit_transparentzonderbolklein2012MAIL][cid:image001.jpg@01D0ADC7.5D66F4F0]
Vertrouwt u liever haar of uw eigen data voor strategische beslissingen?
Ontdek het antwoord en meldt u aan voor onze reeks themaseminars: 15 september, 13 oktober en 8 december 2016 .
Meer informatie en aanmelden via onze website: www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>

Van: Primož Gabrijelčič [mailto:notifications@github.com]
Verzonden: maandag 25 juli 2016 09:43
Aan: gabr42/OmniThreadLibrary <OmniThreadLibrary@noreply.github.com>
CC: Hans Hasenack <Hans@sg-assetmanagement.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)


Also no attachment. :( Please send an email directly to gabr42@gmail.com<mailto:gabr42@gmail.com>, that should work.

**Comment by HHasenack** [comment]
Met vriendelijke groet,

Hans Hasenack

S&G Asset Management
Bijsterhuizen 1160b
6546 AS  NIJMEGEN
Tel. +31 (0) 24 – 645 0006
Fax +31 (0) 24 – 366 0254
www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>
[sgpartnerswit_transparentzonderbolklein2012MAIL][cid:image001.jpg@01D0ADC7.5D66F4F0]
Vertrouwt u liever haar of uw eigen data voor strategische beslissingen?
Ontdek het antwoord en meldt u aan voor onze reeks themaseminars: 15 september, 13 oktober en 8 december 2016 .
Meer informatie en aanmelden via onze website: www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>

Van: Hans Hasenack
Verzonden: maandag 25 juli 2016 11:34
Aan: 'gabr42/OmniThreadLibrary' <reply@reply.github.com>
Onderwerp: RE: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)

It was refused (even by gmail) because of some potential dangerous malware. So I dropped everything from the archive except pas and dpr files.

I sen dit to both addresses now, lets hop it gets through this time. Otherwise I send you the unit test pas file only … :s


Met vriendelijke groet,

Hans Hasenack

S&G Asset Management
Bijsterhuizen 1160b
6546 AS  NIJMEGEN
Tel. +31 (0) 24 – 645 0006
Fax +31 (0) 24 – 366 0254
www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>
[sgpartnerswit_transparentzonderbolklein2012MAIL][cid:image001.jpg@01D0ADC7.5D66F4F0]
Vertrouwt u liever haar of uw eigen data voor strategische beslissingen?
Ontdek het antwoord en meldt u aan voor onze reeks themaseminars: 15 september, 13 oktober en 8 december 2016 .
Meer informatie en aanmelden via onze website: www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/>

Van: Primož Gabrijelčič [mailto:notifications@github.com]
Verzonden: maandag 25 juli 2016 09:43
Aan: gabr42/OmniThreadLibrary <OmniThreadLibrary@noreply.github.com<mailto:OmniThreadLibrary@noreply.github.com>>
CC: Hans Hasenack <Hans@sg-assetmanagement.nl<mailto:Hans@sg-assetmanagement.nl>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Onderwerp: Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)


Also no attachment. :( Please send an email directly to gabr42@gmail.com<mailto:gabr42@gmail.com>, that should work.

**Comment by gabr42** [comment]
Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75)


Nope, just received the email below (to both addresses).

Primož





It was refused (even by gmail) because of some potential dangerous malware. So I dropped everything from the archive except pas and dpr files. 

I sen dit to both addresses now, lets hop it gets through this time. Otherwise I send you the unit test pas file only … :s 


Met vriendelijke groet, 

Hans Hasenack 

S&G Asset Management 
Bijsterhuizen 1160b 
6546 AS NIJMEGEN 
Tel. +31 (0) 24 – 645 0006 
Fax +31 (0) 24 – 366 0254 
www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/> 
[sgpartnerswit_transparentzonderbolklein2012MAIL][cid:image001.jpg@01D0ADC7.5D66F4F0] 
Vertrouwt u liever haar of uw eigen data voor strategische beslissingen? 
Ontdek het antwoord en meldt u aan voor onze reeks themaseminars: 15 september, 13 oktober en 8 december 2016 . 
Meer informatie en aanmelden via onze website: www.sg-assetmanagement.nl<http://www.sg-assetmanagement.nl/> 

Van: Primož Gabrijelčič [mailto:notifications@github.com] 
Verzonden: maandag 25 juli 2016 09:43 
Aan: gabr42/OmniThreadLibrary <OmniThreadLibrary@noreply.github.com> 
CC: Hans Hasenack <Hans@sg-assetmanagement.nl>; Author <author@noreply.github.com> 
Onderwerp: Re: [gabr42/OmniThreadLibrary] TOmniValue does not drop OwnedObject (#75) 


Also no attachment. :( Please send an email directly to gabr42@gmail.com<mailto:gabr42@gmail.com>, that should work.

**Comment by HHasenack** [comment]
[unittests.zip](https://github.com/gabr42/OmniThreadLibrary/files/383213/unittests.zip)

**Comment by HHasenack** [comment]
DId you manage to reproduce the problem?

**Comment by gabr42** [comment]
Didn't have time to look into it yet.

**Comment by gabr42** [comment]
I agree that this is a bug and I agree with your fix. I'll commit it + your unit tests (they all show green here).
