### ISSUE TITLE
Delphinusscript is broken

### ISSUE THREAD

**Issue by Memnarch** [gabr42/OmniThreadLibrary#79]
The recent release adds an extra subdirectory to the Packages directory. However ther Packages-Directory is not copied recursively.

By looking at your Json, i am a bit confused. Isn't it simpler to simply copy everything recursively or are there folders/files you want to exclude? Current Setup looks a bit complicated.

I'd imagine something like:
`        {  
            "folder": "",  
            "recursive": true,  
            "filter": "*;*.*"  
        }`  
as the only directory operation required.

**Comment by Memnarch** [comment]
AFterwards you'll have to recreate the release (delete release + tag, recreate them from the new commit)

**Comment by gabr42** [comment]
Fixed, thanks!

As for the complicated install - I don't remember. I know I tried different approaches and this was the first one that worked.
