### ISSUE TITLE
undefines when building package in 10.1 berlin

### ISSUE THREAD

**Issue by maglex96** [gabr42/OmniThreadLibrary#80]
OtlCommon.pas(3872): E2003 Undeclared identifier: 'DSiGetThreadGroupAffinity'
OtlCommon.pas(4017): E2003 Undeclared identifier: 'DSiGetNumaHighestNodeNumber'
OtlCommon.pas(4027): E2003 Undeclared identifier: 'DSiGetSystemFirmwareTable' OtlCommon.pas(4038): E2003 Undeclared identifier: 'DSiGetNumaProximityNodeEx'

**Comment by gabr42** [comment]
OOops, wrong DSiWin32 was committed. THanks!

I have recreated the release.

**Comment by abdi9x** [comment]
Great....., I'm waiting for this
