### ISSUE TITLE
Scheduling tasks

### ISSUE THREAD

**Issue by PatrickvL** [gabr42/OmniThreadLibrary#81]
This is more a how-to question (on things not easily to be found in the book) than an actual issue; (Unless I'm asking for missing functionality, in which case these questions should be interpreted as feature-requests).

How can a task be setup to repeat a predefined number of times?

How can tasks be scheduled to run on a specific time, for example sixty times per second or once every minute / hour, etc.?

How can tasks be scheduled in such a way that they only run once a set of prerequisites is met?
(For example : a copy task can only be executed once a conversion task and subsequent writer task are finished, while the conversion task starts once every hour.)

How can prerequisites be added and/or removed to/from a task?
Is it possible to build up a complete network of prerequisites, and let the scheduler handle everything?

And by extension : 
Can a task be cancelled when it was unable to meet it's prerequisites?
How can cancelled/aborted/failed tasks be retried? 
How can the number of retries be limitted?
How should tasks that fail all retries be handled?

Thanks in advance!

**Comment by gabr42** [comment]
These are all very problem-specific operations and they should all be handled in your code, not in the OTL.

**Comment by PatrickvL** [comment]
Fair enough.

However, having a more advanced task-scheduler (in contrast to the current implementation which just pops tasks from a queue) could be a valuable addition.

If this is a new concept for OTL, and if it's going to be considered at some point in time, than at least the above could be used as an example of a few use-cases that could be made possible.

**Comment by gabr42** [comment]
Yes, more advanced task scheduler is a possibility and I'll certainly keep your ideas in mind,
