### ISSUE TITLE
error installing 64bit Berlin 10.1 package on version 3.06.1

### ISSUE THREAD

**Issue by maglex96** [gabr42/OmniThreadLibrary#82]
[dcc64 Fatal Error] OtlRegister.pas(58): E2213 Bad packaged unit format: C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp\OmniThreadLibraryRuntime.dcp.OtlEventMonitor - Expected version: 31.0, Windows Unicode(x64) Found version: 31.0, Windows Unicode(x86)

**Comment by gabr42** [comment]
Do a build instead of compile.

**Comment by maglex96** [comment]
I did a build. It fails on the designtime.bpl with the same error as above under 64bit. The runtime.bpl installsunder 64bit  with no problem. Both designtime.bpl and runtime.bpl install correctly under 32bit.

**Comment by gabr42** [comment]
Can you please reload the 3.06.1 release? There was a problem with .dproj files and I recreated the release.

**Comment by maglex96** [comment]
I used the released version 3.06.1 and I still have the same error when I attempt to build 64bit designtime.bpl error:
[dcc64 Fatal Error] OtlRegister.pas(58): E2213 Bad packaged unit format: C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp\OmniThreadLibraryRuntime.dcp.OtlEventMonitor - Expected version: 31.0, Windows Unicode(x64) Found version: 31.0, Windows Unicode(x86)

**Comment by gabr42** [comment]
Do you have old version of OTL package installed? Try removing it (delete it from the disk) and then rebuild the package.

**Comment by maglex96** [comment]
I did a clean install on a different machine that did not have any versions of omnithreadlibrary ever installed. I then installed version 3.06.1 on this new machine. I then did a build of 64 bit and I got the same error. I then did an install of 32bit there were no errors. There is clearly an error in the 64bit build of designtime.bpl Can you suggest anything else?

**Comment by maglex96** [comment]
To futher prove the point I have just installed 3.06.1 in XE7 USING 64BIT THERE WERE NO ERRORS

**Comment by gabr42** [comment]
As I guessed - you have OmniThreadLibrary package active in IDE and that prevents the 64-bit compilation. Remove the OmniThreadLibrary package, restart the IDE and reinstall the package.

**Comment by maglex96** [comment]
What can I say. I have done everything that you ask and I still get the error in 64bit just on the design build and not on the runtime build. If the installation process works for 32 bit (both runtime and designtime) then it must something to do with OmniThreadLibraryRuntime.dcp.OtlEventMonitor it expects to get Windows Unicode(x64) version 31.0 but only finds Windows Unicode(x86) vesrion 31.0. Why can't you create a 64 bit version of this file.

**Comment by maglex96** [comment]
Has any else successfully installed the omnithreadlibrary version 3.0.6.1 under delphi 10.1 Berlin?

**Comment by maglex96** [comment]
Has any else successfully installed the 64BIT omnithreadlibrary version 3.0.6.1 under delphi 10.1 Berlin?

**Comment by gabr42** [comment]
Just noticed - why do you trying to compile design package in 64-bit? Delphi IDE is 32-bit application and can only install 32-bit design package. Only runtime package needs to be compiled for 64 bit.

**Comment by gabr42** [comment]
No, IDE is only 32-bit, but it can create 64-bit applications.

It would be better to ask your question here: https://plus.google.com/communities/112307748950248514961
More people will see it and maybe somebody will immediately know what is escaping me.
