### ISSUE TITLE
Question: Is the latest OTL supposed to be compatible with XP?

### ISSUE THREAD

**Issue by edwinyzh** [gabr42/OmniThreadLibrary#83]
Just noticed this release note:
[Programs using OtlCommon can be started on Windows XP](https://github.com/gabr42/OmniThreadLibrary/commit/df327a814307a5e333e671e06b07c6ac5732aa6f)

IIRC, OTL is **supposed ** to work under Windows XP. Is my assumption correct? Thanks.

**Comment by gabr42** [comment]
Yes, it is _supposed_ to work, but versions 3.06 and 3.06.1 had a bug that prevented that from happening.
