### ISSUE TITLE
Example of FPC/Linux threading class

### ISSUE THREAD

**Issue by the-Arioch** [gabr42/OmniThreadLibrary#84]
Not actually a bug, for informational purposes.
People asked about point OTL to different platforms like MacOS and Linux, but usually they luck competence to do it.

http://www.sql.ru/forum/actualutils.aspx?action=gotomsg&tid=1050286&msg=19818861

Attached down the link is a very different threading library for Delphi and FPC, Windows and Linux.
It has a different high-level ideology, but its low-level - it's selection and use patterns of OS API - can be a good reference point to any potential OTL/FPC/Linux port attempt.

**Comment by gabr42** [comment]
Stored, thanks.
