### ISSUE TITLE
OtlThreadPool.pas -> 2.15a

### ISSUE THREAD

**Issue by hsvandrew** [gabr42/OmniThreadLibrary#86]
In my opinion, there is a major bug in the thread pool regarding worker timeouts.

I have been creating a thread pool in code, and perhaps I didn't follow some instructions correctly but I do it like this:

FConnectionPool := CreateThreadPool('TSomething:'+inttostr(application.Handle));
FConnectionPool.SetThreadDataFactory(CreateThreadData);
FConnectionPool.MaxExecuting := 10;
FConnectionPool.IdleWorkerThreadTimeout_sec := 60*5*1000;

Now what you would expect to happen here is that the IdleWorkerThreadTimeout is 30000. However this is not the case because the TOTPWorker.Initialize hasn't executed yet. So the Timeout value is set on the worker object, then later on TOTPWorker.Initialize kills it and replaces it with the default value.

The init of the Timeout/wait on terminate values should be moved from .Initialize to .create

constructor TOTPWorker.Create(const name: string; uniqueID: int64; pool: IOmniThreadPool );
begin
  inherited Create;
  owName := name;
  owUniqueID := uniqueID;
  owPool := pool;
  IdleWorkerThreadTimeout_sec.Value := CDefaultIdleWorkerThreadTimeout_sec;
  WaitOnTerminate_sec.Value := CDefaultWaitOnTerminate_sec;
end; 

I feel this is a major problem as many people may think they have a pool with threads that are acting as a pool and holding for a longer period of time (just as they have set) when in fact they are being freed after just 10 seconds.

**Comment by gabr42** [comment]
I fully agree with your analysis.

This is now fixed.
