### ISSUE TITLE
Reference docs?

### ISSUE THREAD

**Issue by sanjayssk** [gabr42/OmniThreadLibrary#87]
I can't find any reference document where I can see all the methods of a class described. The download only contains VSD files with diagrams. Am I missing something?

Thanks.

**Comment by sanjayssk** [comment]
Never mind. Bought the book. BTW, I can't figure out the following:

`procedure TForm1.oemTaskTerminated(const task: IOmniTaskControl);`

In the above procedure, I want to get the Worker object class from the task parameter. Is it possible to do that? The reason is that I have some properties to identify the task worker object, and I want to access them to see which task has terminated. I posted this in stackoverflow already but didn't get a response yet.

Thanks.

**Comment by gabr42** [comment]
Can you paste here a link to the SO question? I'll answer there.

**Comment by sanjayssk** [comment]
[http://stackoverflow.com/questions/41680982/how-to-get-worker-from-the-iomnitaskcontrol](url)
