### ISSUE TITLE
Memory Leak in Thread Pool factory when exception raised

### ISSUE THREAD

**Issue by jsmart73** [gabr42/OmniThreadLibrary#88]
See example code:

```
program Project2;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  otlTaskControl,
  otlTask,
  otlThreadPool;

var
  Pool: IOmniThreadPool;

function AFactory: IInterface;
begin
  raise Exception.Create('Error Message');
end;

begin
  try
    ReportMemoryLeaksOnShutdown := True;

    Pool := CreateThreadPool('Test');
    Pool.SetThreadDataFactory(AFactory);

    CreateTask(procedure (const task: IOmnitask) begin end).Schedule(Pool);
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
```
Results in memory leak - TBits, TOmniIntegerSet and TOTPWorkItem, TOmniTask (run above in console to see details)

**Comment by gabr42** [comment]
I agree that is not the best solution. The real question, however, is - what to do if a factory throws an exception? There is probably a no clean way to continue execution.

**Comment by jsmart73** [comment]
No, you're right.  There is no clean way.
For me, if possible and not having thought too much about it, could we just clean up the objects that are cleaning and execute the OnTerminate event (if there is one)?
