### ISSUE TITLE
Service app

### ISSUE THREAD

**Issue by GitStorageOne** [gabr42/OmniThreadLibrary#92]
Hello! I have same question as here:
http://stackoverflow.com/questions/22451501/can-omnithreadlibrary-be-used-in-a-delphi-windows-service

**Comment by gabr42** [comment]
There's an example in the repo showing how to use OTL from a service.  (In short - without any problems.)

https://github.com/gabr42/OmniThreadLibrary/tree/master/tests/63_Service
