### ISSUE TITLE
Memory leaks on Parallel.&For(0, uu).Execute(

### ISSUE THREAD

**Issue by DoctorLai** [gabr42/OmniThreadLibrary#98]
I think there is definitly some memory leaks of Parallel.&For
because I try to replace it with serial version and it is fine, but if I keep it running for minutes, the memory grows unexepctedly.

**Comment by gabr42** [comment]
Please create a small example that will exhibit the problem.

**Comment by DoctorLai** [comment]
Not all Parallel.For has problems.
I am building a COM DLL that calls 1 API many many times. 
in my case, I remove all code inside Parallel For (so it is basically empty parallel for skeleton) and OTL still eats memory.
I then  replace OTL with the System.Threading.TParallel.For,   the problem goes away.
So, I think there is definitely something not freed-up if you call one function that has a parallel.for many many times.

**Comment by DoctorLai** [comment]
I use FastMM, and it doesn't report memory leak because somehow before DLL is unloaded,  OTL frees-up memory.
However,  if you have something like this:

for i := 1 to  10000 do // lots of calls to
     some_function_has_parallel_for;

then the memory will not be freed between each call in the for, which causes out-of-memory exception.

As I mentioned above,  the System.Threading.TParallel   does not have this problem. You could try the simplest example with:

Parallel.&For(0, 100).Execute(
  procedure (i: integer)
  begin
    // do nothing
  end;
);

**Comment by gabr42** [comment]
As I said, prepare a compilable example that exhibits a problem and I'll look into it.

**Comment by DoctorLai** [comment]
Here is the example to see the memory keeps eating until OOM,
Please note, if I replace Parallel.For using TParallel.For from System.Threading, the memory is stabilized at 650MB, which is acceptable.

`program TestParallelFor;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.Threading,
  Windows,
  System.SysUtils,
  OtlParallel in 'OmniThreadLibrary\OtlParallel.pas';

procedure Test1;
const
  luckynumber = 8;
var
  data: array of array of array of int64;
  a, b, c: integer;
begin
  SetLength(data, 300, 300, 100);
  Parallel.&For(0, High(data)).Execute(
    procedure (i: integer)
    var
      j, k: integer;
    begin
      for j := 0 to High(data[i]) do
      begin
        for k := 0 to High(data[i][j]) do
        begin
          data[i][j][k] := luckynumber;
        end;
      end;
    end);
  for a := 0 to High(data) do
  begin
    for b := 0 to High(data[a]) do
    begin
      for c := 0 to High(data[a][b]) do
      begin
        if (data[a][b][c] <> luckynumber) then
        begin
          raise Exception.Create(IntToStr(data[a][b][c]));
        end;
      end;
    end;
  end;
end;

var
  i: integer;
begin
  for i := 0 to 100 do
  begin
    Writeln('Test Run = ', i);
    Test1;
    Sleep(500);
  end;
  Writeln('Finished.');
  Readln;
end.`

**Comment by DoctorLai** [comment]
With the code correctly formatted as below.

```
program TestParallelFor;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.Threading,
  Windows,
  System.SysUtils,
  OtlParallel in 'OmniThreadLibrary\OtlParallel.pas';

procedure Test1;
const
  luckynumber = 8;
var
  data: array of array of array of int64;
  a, b, c: integer;
begin
  SetLength(data, 300, 300, 100);
  Parallel.&For(0, High(data)).Execute(
    procedure (i: integer)
    var
      j, k: integer;
    begin
      for j := 0 to High(data[i]) do
      begin
        for k := 0 to High(data[i][j]) do
        begin
          data[i][j][k] := luckynumber;
        end;
      end;
    end);
  for a := 0 to High(data) do
  begin
    for b := 0 to High(data[a]) do
    begin
      for c := 0 to High(data[a][b]) do
      begin
        if (data[a][b][c] <> luckynumber) then
        begin
          raise Exception.Create(IntToStr(data[a][b][c]));
        end;
      end;
    end;
  end;
end;

var
  i: integer;
begin
  for i := 0 to 100 do
  begin
    Writeln('Test Run = ', i);
    Test1;
    Sleep(500);
  end;
  Writeln('Finished.');
  Readln;
end.
```

**Comment by gabr42** [comment]
A console-based OTL program requires manually implemented message loop. See test 62_Console for an example.

Add this to your program:

```
procedure ProcessMessages;
var
  Msg: TMsg;
begin
  while integer(PeekMessage(Msg, 0, 0, 0, PM_REMOVE)) <> 0 do begin
    TranslateMessage(Msg);
    DispatchMessage(Msg);
  end;
end;
```

and modify the test run loop:
```
  for i := 0 to 100 do
  begin
    Writeln('Test Run = ', i);
    Test1;
    ProcessMessages;
    Sleep(500);
  end;
```

That will fix memory leaks.

**Comment by DoctorLai** [comment]
1.  It does not make much sense for a console application or a pure DLL to "ProcessMessages", as this is related to UI
2.  My understanding is that the OTL is a replacement for System.Threading, so this actually changes the 'default' behavior as is expected.
3.  I appreciate your solution, but I think this is more like a 'workaround',  at least not an elegant solution. 
4.  I could just add Application.ProcessMessages which is essentially the same as your ProcessMessages function.

**Comment by gabr42** [comment]
Re 1,2,3: That is how OTL works.
Re 4: Yes, you could.

**Comment by DoctorLai** [comment]
Thanks!
I guess it wouldn't hurt to call the ProcessMessages between iterations.  
btw, 👍  for the tiny memory consumptions in the above test code, my testings reveal that, this example OTL uses less than 10MB while the System.Threading.TParallel.For uses more than 650MB!!!
